# Generated by Django 4.2.1 on 2023-05-13 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0002_remove_movie_sociallink_movie_socialink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='createdtime',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2023, 5, 13, 7, 42, 26, 755652), null=None),
        ),
    ]
