# Generated by Django 4.2.1 on 2023-05-15 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0006_alter_movie_createdtime_alter_movie_moviesrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='linkurl',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='createdtime',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2023, 5, 15, 11, 25, 20, 614546), null=None),
        ),
    ]
