# Generated by Django 4.2.1 on 2023-05-16 00:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0007_link_linkurl_alter_movie_createdtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='createdtime',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2023, 5, 15, 19, 35, 48, 563495), null=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='moviesrc',
            field=models.FileField(upload_to='movies'),
        ),
    ]
