# Generated by Django 4.2.1 on 2023-05-17 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0009_alter_movie_createdtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='createdtime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
